<div class="content-wrapper">
    <h1>Rozvrh pro - <?= $_SESSION['login'] ?></h1>
</div>
<div class="schedule">
    <?php
    $schedule = $_SESSION['schedule'];
    echo '<div class="day" >';

        $timestamps = $_SESSION['timeStamps'];
        foreach ($timestamps as $stamp) {
            echo '<div class="lesson-wrapper">';
                echo '<div class="lesson">';
                    echo "<h1 class='subject'>" . $stamp['order'] . "</h1>";
                    echo "<p class='from'>" . $stamp['from'] . "</p>";
                    echo "<p class='to'>" . $stamp['to'] . "</p>";
                echo '</div>';
            echo '</div>';
        }

    echo '</div>';

    foreach ($schedule as $day) {
        echo '<div class="day">';

        foreach ($day->day as $lessonWrap) {
            $size = count($lessonWrap->lessons) > 1 ? "x".count($lessonWrap->lessons) : '';
            echo "<div class='lesson-wrapper $size'>";

                foreach ($lessonWrap->lessons as $lesson) {
                    $lesson->createHtml();
                }

            echo '</div>';
        }

        echo '</div>';
    }
    ?>
</div>