<div class="content-wrapper">
    <h1>Rozvrh pro - <?= $_SESSION['login'] ?></h1>
</div>
<div class="schedule">
    <?php
    $schedule = $_SESSION['schedule'];
    echo '<div class="day" >';
    $timestamps = $_SESSION['timeStamps'];
    foreach ($timestamps as $stamp) {
        echo '<div class="lesson-wrapper">';
            echo '<div class="lesson">';
                echo "<h1 class='subject'>" . $stamp['order'] . "</h1>";
                echo "<p class='from'>" . $stamp['from'] . "</p>";
                echo "<p class='to'>" . $stamp['to'] . "</p>";
            echo '</div>';
        echo '</div>';
    }
    echo '</div>';
    foreach ($schedule as $day) {
        echo '<div class="day">';
        foreach ($day->day as $lessonWrap) {
            $size = count($lessonWrap->lessons) > 1 ? "x".count($lessonWrap->lessons) : '';
            echo "<div class='lesson-wrapper $size'>";
            foreach ($lessonWrap->lessons as $lesson) {
                $free = $lesson->free ? 'free' : '';
                $change = $lesson->change ? 'change' : '';
                echo "<div class='lesson $free $change'>";
                if (property_exists($lesson, 'subject'))
                    $combined = $lesson->subject;
                    if ($lesson->week !== '') {
                        $combined = $lesson->week.$lesson->subject;
                    }
                    echo "<p class='subject'>$combined</p>";
                if (property_exists($lesson, 'room'))
                    echo "<p class='room'>$lesson->room</p>";
                if (property_exists($lesson, 'teacher'))
                    echo "<p class='teacher'>$lesson->teacher</p>";
                if (property_exists($lesson, 'group'))
                    echo "<p class='group'>$lesson->group</p>";
                echo '</div>';
            }
            echo '</div>';
        }
        echo '</div>';
    }
    ?>
</div>